version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true
  sass:
    image: larryprice/sass
    volumes:
      - ./public/css:/src
